CREATE TABLE car (
    id SERIAL PRIMARY KEY,
    order INTEGER DEFAULT 0,
    brand_id INTEGER NOT NULL REFERENCES brand(id) ON DELETE RESTRICT,
    name VARCHAR(255) NOT NULL,
    manufacture_year INTEGER DEFAULT 20,
    price FLOAT NOT NULL,
    engine_type_id INTEGER NOT NULL REFERENCES engine_type(id) ON DELETE RESTRICT,
    acceleration FLOAT NOT NULL,
    power_reserver_from INTEGER NOT NULL,
    power_reserver_to INTEGER NOT NULL,
    length FLOAT NOT NULL,
    width FLOAT NOT NULL,
    height FLOAT NOT NULL,
    num_of_places INTEGER NOT NULL,
    max_speed INTEGER NOT NULL,
    drive_unit_id INTEGER NOT NULL REFERENCES drive_unit(id) ON DELETE RESTRICT,
    battery_capacity FLOAT NOT NULL,
    charging_speed FLOAT NOT NULL,
    speed_in VARCHAR(255) CHECK (speed_in IN ('minutes', 'hours')),
    desc_1 TEXT NOT NULL,
    desc_2 TEXT NOT NULL,
    is_featured BOOLEAN DEFAULT FALSE,
    status VARCHAR(255) CHECK (status IN ('active', 'deactive')),
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);